version: '3'
services:
  web:
    build: './'
    depends_on:
      - 'nearbyatt'
      - 'reviews'
      - 'carousel'
      - 'experiences'
    ports:
      - '80:8080'

  # nearbyatt:
  #   image: codacasey/fecpoxynearbyatt:firsttry
  #   depends_on:
  #     - 'database'
  #   ports:
  #     - '3013:3013'
  # experiences:
  #   image: codacasey/fecproxyexperiencetwo:firsttry
  #   depends_on:
  #     - 'database'
  #   ports:
  #     - '3014:3014'

  reviews:
    image: cschmidt331/fec_proxy_server:reviews_service
    depends_on:
      - 'database'
    ports:
      - '3004:3004'
  # carousel:
  #   image: codacasey/fecproxycarousel:firsttry
  #   depends_on:
  #     - 'database'
  #   ports:
  #     - '3012:3012'




